#! /bin/sh

### BEGIN INIT INFO
# Provides:		rc-stickynote-housekeeping
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:	        1 6
# Short-Description:	Waveshare e-Print Display housekeeping
### END INIT INFO

set -e

displayer=/usr/local/bin/rc_stickynote_displayer

case "$1" in
    start)
    # This used to do show-ips, but I don't want to worry about boot-time
    # races between this and the main displayer.
	;;

    stop)
	"$displayer" clear-and-sleep
	;;

    reload|force-reload|restart|try-restart)
	"$displayer" clear-and-sleep
	;;

    status)
	"$displayer" show-ips
	;;

    *)
	echo "usage: $0 {start|stop|reload|force-reload|restart|try-restart|status}" || true
	exit 1
esac

exit 0
